input_data_path: "data/raw/DATA.csv"
output_model_path: "models/DecisionTreeClassifier.pkl"
metric_path: "models/DecisionTreeClassifier_metrics_train.json"
output_transformer_path: "models/DecisionTreeClassifier_transformer.pkl"

splitting_params:
  val_size: 0.2
  random_state: 0

train_params:
  model_type: "DecisionTreeClassifier"
  random_state: 0

feature_params:
  categorical_features:
    - "Systemic Illness"
    - "Rectal Pain"
    - "Sore Throat"
    - "Penile Oedema"
    - "Oral Lesions"
    - "Solitary Lesion"
    - "Swollen Tonsils"
    - "HIV Infection"
    - "Sexually Transmitted Infection"
  features_to_drop:
    - "Patient_ID"
  target_col:
    - "MonkeyPox"





