input_data_path: "data/raw/DATA.csv"
model_path: "models/LogisticRegression.pkl"
predict_path: "models/LogisticRegression.csv"
transformer_path: "models/LogisticRegression_transformer.pkl"


target_in_dataset: True
target: "MonkeyPox"
feature_params:
  categorical_features:
    - "Systemic Illness"
    - "Rectal Pain"
    - "Sore Throat"
    - "Penile Oedema"
    - "Oral Lesions"
    - "Solitary Lesion"
    - "Swollen Tonsils"
    - "HIV Infection"
    - "Sexually Transmitted Infection"
  features_to_drop:
    - "Patient_ID"
  target_col:
    - "MonkeyPox"
