input_data_path: "data/raw/train.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 0
train_params:
  model_type: "RandomForestRegressor"
feature_params:
  categorical_features:
    - "Systemic Illness"
    - "Rectal Pain"
    - "Sore Throat"
    - "Penile Oedema"
    - "Oral Lesions"
    - "Solitary Lesion"
    - "Swollen Tonsils"
    - "HIV Infection"
    - "Sexually Transmitted Infection"
    features_to_drop:
      - "Patient_ID"
    target_col:
      - "MonkeyPox"

downloading_params:
  s3_bucket: for-dvc
  paths:
    - train.csv
    - test.csv
  output_folder: "data/raw/"
